[theme]
primaryColor="#ff0033"  # Bright neon red for action buttons
backgroundColor="#0b132b"  # Deep cosmic blue for a futuristic touch
secondaryBackgroundColor="#1c2541"  # A muted tech-blue for depth
textColor="#f5f5f5"  # Soft white for cyber readability
font="sans serif"